### ISSUE TITLE
"list index out of range" error on installation

### ISSUE THREAD

**Issue by Hombre57** [Tilapiatsu/blender-Universal_Multi_Importer#4]
I drag and dropped the extension in Blender 4.2.0, and get an error : "list index out of range. It seem to be installed but not active, since I can find it in `Preferences > Add-ons`. Clicking on the checkbox raise the same error.

I've added the `print("Path added:", path)` debug statement after line 449 of `C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\utils\__init__.py`

Then here is the complete log with the following steps :

1. Open Blender 4.2.0
2. Delete the Cube
3. Open Preferences > Add-ons
4. Click on the Universal Importer checkbox (unchecked for now)

```
Path added: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts
Path added: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\presets
Path added: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts
Path added: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts
Infos: 1 objet(s) supprimé(s)  [CUBE DELETED]
Path added: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts
Path added: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts
Path added: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\addon_utils.py", line 401, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\universal_multi_importer\__init__.py", line 2, in <module>
    from .umi_const import ADDON_FOLDER_PATH, ADDON_PACKAGE
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\universal_multi_importer\umi_const.py", line 6, in <module>
    AUTOSAVE_PATH = os.path.join(pathlib.Path(bpy.utils.script_paths()[1]).parent.absolute(), 'autosave')
                                              ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Here stops my investigations.

System : Windows 10 / 64-bits

**Comment by Tilapiatsu** [comment]
Hi @Hombre57 !
Thanks for reaching out ! I'm sorry for the inconvenience.

I never had this issue, and was not able to reproduce it, but I've made some change to the addon that I think should fix it. 

Here is the modified addon : 
[tila_universal_multi_importer_2.1.5_RC_AddonDependencyChecker.zip](https://github.com/user-attachments/files/16333287/tila_universal_multi_importer_2.1.5_RC_AddonDependencyChecker.zip)

Can you please :

- uninstall the previous version
- restart blender
- install this new version
- check and let me know if it fixes the issue

If everything is fine for you, I'll make it a proper release on extension website.

Thanks ! Have a good day

**Comment by Hombre57** [comment]
Hi @Tilapiatsu,

This new version works fine, thank you. I installed and launched it without error. You'll be able to update the bad review of the user who experienced that as well 😉

**Comment by Tilapiatsu** [comment]
Thanks for the confirmation :)
The new release is now published on both Github and Extension platform
